name: PMD Analysis via Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pmd-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build Docker Image for PMD
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: pmd-apex:latest

      - name: Run PMD Analysis in Container
        run: |
          # Create a directory on the host to store the PMD report
          mkdir -p $GITHUB_WORKSPACE/pmd-reports

          # Run the container, mount the repository's 'src' folder into the container's /src,
          # and output the PMD report to a location accessible on the host.
          docker run --rm -v "${{ github.workspace }}/src:/src" -v "$GITHUB_WORKSPACE/pmd-reports:/reports" pmd-apex:latest

      - name: Upload PMD Report Artifact
        uses: actions/upload-artifact@v3
        with:
          name: pmd-report
          path: pmd-reports/pmd-report.html
