name: PMD Analysis on Apex Code

on:
  push:
    branches:
      - main

jobs:
  setup-pmd:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: 8
        distribution: temurin
        architecture: x64

    - name: Install PMD
      run: |
        # Download PMD binary release
        curl -L https://github.com/pmd/pmd/releases/download/pmd_releases%2F6.40.0/pmd-bin-6.40.0.zip -o pmd.zip
        unzip pmd.zip -d /opt/
        rm pmd.zip

        # Add PMD to PATH and source it immediately in the current shell
        echo "/opt/pmd-bin-6.40.0/bin" >> $GITHUB_PATH
        source /opt/pmd-bin-6.40.0/bin/pmd  # Ensure PMD command is accessible in this shell

    - name: Verify PMD installation
      run: |
        # Verify PMD is available in the PATH
        pmd -v  # This should print PMD version

    - name: Run PMD Analysis on Apex Code
      run: |
        # Run PMD analysis with the provided ruleset
        pmd check -d src/ -R apex-ruleset.xml -f html -r pmd-report.html
        ls -alh pmd-report.html  # This will list the file to verify if it was created
      env:
        JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/8.0.442-6/x64
