name: PMD Apex Code Analysis

on:
  push:
    branches:
      - main  # Or adjust to the branch you want to monitor
  pull_request:
    branches:
      - main  # Or adjust to the branch you want to monitor

jobs:
  pmd:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up JDK 8 (Required for PMD)
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
        architecture: x64

    - name: Install PMD
      run: |
        # Download PMD binaries
        wget https://github.com/pmd/pmd/releases/download/pmd_releases/6.40.0/pmd-bin-6.40.0.zip
        unzip pmd-bin-6.40.0.zip

        # Move PMD to a specific location
        sudo mv pmd-bin-6.40.0 /opt/pmd

        # Check if PMD is installed and what files are in the /opt/pmd/bin directory
        ls -alh /opt/pmd/bin/  # This will list files in the bin directory

        # Debugging: Ensure that PMD is present
        ls -alh /opt/pmd/bin/pmd

        
    - name: Run PMD Analysis on Apex Code
      run: |
        # Assuming your Apex code is in the 'src' folder
        /opt/pmd/bin/pmd -d src/ -R apex-ruleset.xml -f html -r pmd-report.html
        ls -alh pmd-report.html  # Verify if the file exists

    - name: Upload PMD Report as an Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: pmd-report
        path: pmd-report.html

  download-artifact:
    runs-on: ubuntu-latest
    needs: pmd
    steps:
    - name: Download PMD Report Artifact
      uses: actions/download-artifact@v2
      with:
        name: pmd-report
        path: ./pmd-report
