name: PMD Analysis on Apex Code

on:
  push:
    branches:
      - main

jobs:
  setup-pmd:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: 8
        distribution: temurin
        architecture: x64
        
    - name: Extract PMD
      run: |
        curl -L https://github.com/pmd/pmd/archive/refs/tags/pmd_releases/7.12.0.zip -o pmd.zip
        unzip pmd.zip -d /opt

    - name: List contents of PMD extracted directory
      run: ls -alh /opt/pmd-*

    - name: List contents of OPT  directory
      run: ls -al /opt/

    - name: Add PMD to PATH
      run: echo "/opt/pmd-7.12.0/bin" >> $GITHUB_PATH

    - name: Print PATH for debugging
      run: echo $PATH

    - name: Ensure PMD is executable
      run: chmod +x /opt/pmd-7.12.0/bin/pmd

    - name: Verify PMD installation
      run: |
        if [ ! -f /opt/pmd-7.12.0/bin/pmd ]; then
          echo "PMD executable not found!";
          exit 1;
        fi
        echo "PMD found!"

    - name: Run PMD with full path
      run: /opt/pmd-7.12.0/bin/pmd -v
