name: PMD Analysis on Apex Code

on:
  push:
    branches:
      - main

jobs:
  setup-pmd:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: 8
        distribution: temurin
        architecture: x64

    - name: Install Latest PMD
      run: |
        # Fetch the latest stable version from GitHub
        LATEST_VERSION=$(curl -s https://api.github.com/repos/pmd/pmd/releases/latest | jq -r .tag_name)
        
        # Download the latest PMD binary release
        curl -L "https://github.com/pmd/pmd/releases/download/${LATEST_VERSION}/pmd-bin-${LATEST_VERSION}.zip" -o pmd.zip
        unzip pmd.zip -d /opt/
        rm pmd.zip

        # List the contents of the extracted directory to verify the PMD path
        ls -alh /opt/pmd-bin-*

        # Add PMD to PATH
        echo "/opt/pmd-bin-${LATEST_VERSION}/bin" >> $GITHUB_PATH

    - name: Verify PMD installation
      run: |
        # Verify PMD is available in the PATH
        pmd -v  # This should print the PMD version

    - name: Run PMD Analysis on Apex Code
      run: |
        # Run PMD analysis with the provided ruleset
        pmd check -d src/ -R apex-ruleset.xml -f html -r pmd-report.html
        ls -alh pmd-report.html  # This will list the file to verify if it was created
      env:
        JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/8.0.442-6/x64
